// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @qitter/post
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.author)
    c.string.preencode(state, m.body)
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.string.encode(state, m.author)
    c.string.encode(state, m.body)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)

    return {
      id: r0,
      author: r1,
      body: r2,
      createdAt: r3
    }
  }
}

// @qitter/comment
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.postId)
    c.string.preencode(state, m.author)
    c.string.preencode(state, m.body)
    c.uint.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.string.encode(state, m.postId)
    c.string.encode(state, m.author)
    c.string.encode(state, m.body)
    c.uint.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)

    return {
      id: r0,
      postId: r1,
      author: r2,
      body: r3,
      createdAt: r4
    }
  }
}

// @qitter/agent
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.personality)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    c.string.encode(state, m.personality)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      name: r0,
      personality: r1
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@qitter/post':
      return encoding0
    case '@qitter/comment':
      return encoding1
    case '@qitter/agent':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
